### PR TITLE
Remove Magma dependency by using CuSolver Routines

### PR DESCRIPTION
**Pull request by yingjerkao**
This PR attempts to remove the Magma dependency by replacing magma routines with the corresponding cusolver ones. 

It compiles CUDA 11.8, CuTensor 2.0.2.5, CuQuantum 24.08.0.5.

### CODE REVIEW

**Comment by jeffry1829** [comment]
> It looks like the tests and coverage don't cover the gpu version?

Yes, one possible option is that we might need to link some machine to github action

**Comment by jeffry1829** [comment]
I'll push test for Det later(along with some fixes), however, cusolver getrf is ridiculously slow, might investigate more

**Comment by jeffry1829** [comment]
Nevermind, I didn't use cutensor and cuquantum

**Comment by IvanaGyro** [comment]
@jeffry1829  Could you create another PR for https://github.com/Cytnx-dev/Cytnx/pull/483/commits/35c95aa2296d8a37afb56dab50dddbb38d04070d ? So this PR doesn't have to wait for the commit for fixing the Det.

**Comment by jeffry1829** [comment]
> @jeffry1829 Could you create another PR for [35c95aa](https://github.com/Cytnx-dev/Cytnx/commit/35c95aa2296d8a37afb56dab50dddbb38d04070d) ? So this PR doesn't have to wait for the commit for fixing the Det.

Reverted

**Comment by yingjerkao** [comment]
Fix #482

**Pull request merged**
